# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(default='manager', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='fgd@gdg.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default=432342, max_length=50),
            preserve_default=False,
        ),
    ]
