# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0002_auto_20160214_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('assettype', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
