# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0003_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='assetdistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberName', models.CharField(choices=[('Mr Green', 'green'), ('Mr Yellow', 'yellow'), ('Mr Brown', 'brown'), ('Mr Gray', 'gray')], max_length=3)),
            ],
        ),
    ]
