# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0005_auto_20160214_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetapp.Asset')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetapp.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='assetdistribution',
        ),
    ]
